Traceback (most recent call last):
  File "/home/ibafend/Bureau/Bitcoin Network Measurements Tools/Bitcoin_Node_Discovery/bin/Bitcoin_Crawler/Network/P2P_Connection.py", line 274, in handler_thread
    self.handle_msg(msg)
  File "/home/ibafend/Bureau/Bitcoin Network Measurements Tools/Bitcoin_Node_Discovery/bin/Bitcoin_Crawler/Network/P2P_Connection.py", line 575, in handle_msg
    self.treat_getaddr_msg(rcv_msg)
  File "/home/ibafend/Bureau/Bitcoin Network Measurements Tools/Bitcoin_Node_Discovery/bin/Bitcoin_Crawler/Network/P2P_Connection.py", line 678, in treat_getaddr_msg
    self._network_manager.send_peers(self)
  File "/home/ibafend/Bureau/Bitcoin Network Measurements Tools/Bitcoin_Node_Discovery/bin/Bitcoin_Crawler/Network/Network_Manager.py", line 200, in send_peers
    ips = self._measurements_manager.get_known_ips()
AttributeError: 'Measurements_Manager' object has no attribute 'get_known_ips'


